language: python

install:
  - curl -L https://deno.land/x/install/install.py | python - v0.2.7
  - export PATH="$HOME/.deno/bin:$PATH"

services:
  - postgresql

before_script:
  - psql -c "DROP DATABASE IF EXISTS deno_postgres; CREATE DATABASE deno_postgres OWNER deno_postgres;" -U postgres

script:
  - deno test.ts