language: python

install:
  - curl -L https://deno.land/x/install/install.py | python - v0.2.7
  - export PATH="$HOME/.deno/bin:$PATH"

services:
  - postgresql

before_script:
  - psql -f tests/before_script.sql -U postgres

script:
  - deno test.ts --allow-net